`include "B_BITSLICE_CONTROL_defines.vh"

reg [`BITSLICE_CONTROL_DATA_SZ-1:0] ATTR [0:`BITSLICE_CONTROL_ADDR_N-1];
reg [64:1] CTRL_CLK_REG = CTRL_CLK;
reg [32:1] DIV_MODE_REG = DIV_MODE;
reg [56:1] EN_CLK_TO_EXT_NORTH_REG = EN_CLK_TO_EXT_NORTH;
reg [56:1] EN_CLK_TO_EXT_SOUTH_REG = EN_CLK_TO_EXT_SOUTH;
reg [40:1] EN_DYN_ODLY_MODE_REG = EN_DYN_ODLY_MODE;
reg [40:1] EN_OTHER_NCLK_REG = EN_OTHER_NCLK;
reg [40:1] EN_OTHER_PCLK_REG = EN_OTHER_PCLK;
reg [40:1] IDLY_VT_TRACK_REG = IDLY_VT_TRACK;
reg [40:1] INV_RXCLK_REG = INV_RXCLK;
reg [40:1] ODLY_VT_TRACK_REG = ODLY_VT_TRACK;
reg [40:1] QDLY_VT_TRACK_REG = QDLY_VT_TRACK;
reg [5:0] READ_IDLE_COUNT_REG = READ_IDLE_COUNT;
reg [48:1] REFCLK_SRC_REG = REFCLK_SRC;
reg [7:0] ROUNDING_FACTOR_REG = ROUNDING_FACTOR;
reg [40:1] RXGATE_EXTEND_REG = RXGATE_EXTEND;
reg [64:1] RX_CLK_PHASE_N_REG = RX_CLK_PHASE_N;
reg [64:1] RX_CLK_PHASE_P_REG = RX_CLK_PHASE_P;
reg [56:1] RX_GATING_REG = RX_GATING;
reg [56:1] SELF_CALIBRATE_REG = SELF_CALIBRATE;
reg [40:1] SERIAL_MODE_REG = SERIAL_MODE;
reg [32:1] SIM_SPEEDUP_REG = SIM_SPEEDUP;
real SIM_VERSION_REG = SIM_VERSION;
reg [56:1] TX_GATING_REG = TX_GATING;

initial begin
ATTR[`BITSLICE_CONTROL__CTRL_CLK] = CTRL_CLK;
ATTR[`BITSLICE_CONTROL__DIV_MODE] = DIV_MODE;
ATTR[`BITSLICE_CONTROL__EN_CLK_TO_EXT_NORTH] = EN_CLK_TO_EXT_NORTH;
ATTR[`BITSLICE_CONTROL__EN_CLK_TO_EXT_SOUTH] = EN_CLK_TO_EXT_SOUTH;
ATTR[`BITSLICE_CONTROL__EN_DYN_ODLY_MODE] = EN_DYN_ODLY_MODE;
ATTR[`BITSLICE_CONTROL__EN_OTHER_NCLK] = EN_OTHER_NCLK;
ATTR[`BITSLICE_CONTROL__EN_OTHER_PCLK] = EN_OTHER_PCLK;
ATTR[`BITSLICE_CONTROL__IDLY_VT_TRACK] = IDLY_VT_TRACK;
ATTR[`BITSLICE_CONTROL__INV_RXCLK] = INV_RXCLK;
ATTR[`BITSLICE_CONTROL__ODLY_VT_TRACK] = ODLY_VT_TRACK;
ATTR[`BITSLICE_CONTROL__QDLY_VT_TRACK] = QDLY_VT_TRACK;
ATTR[`BITSLICE_CONTROL__READ_IDLE_COUNT] = READ_IDLE_COUNT;
ATTR[`BITSLICE_CONTROL__REFCLK_SRC] = REFCLK_SRC;
ATTR[`BITSLICE_CONTROL__ROUNDING_FACTOR] = ROUNDING_FACTOR;
ATTR[`BITSLICE_CONTROL__RXGATE_EXTEND] = RXGATE_EXTEND;
ATTR[`BITSLICE_CONTROL__RX_CLK_PHASE_N] = RX_CLK_PHASE_N;
ATTR[`BITSLICE_CONTROL__RX_CLK_PHASE_P] = RX_CLK_PHASE_P;
ATTR[`BITSLICE_CONTROL__RX_GATING] = RX_GATING;
ATTR[`BITSLICE_CONTROL__SELF_CALIBRATE] = SELF_CALIBRATE;
ATTR[`BITSLICE_CONTROL__SERIAL_MODE] = SERIAL_MODE;
ATTR[`BITSLICE_CONTROL__SIM_SPEEDUP] = SIM_SPEEDUP;
ATTR[`BITSLICE_CONTROL__SIM_VERSION] = $realtobits(SIM_VERSION);
ATTR[`BITSLICE_CONTROL__TX_GATING] = TX_GATING;
end

always @(trig_attr) begin
CTRL_CLK_REG = ATTR[`BITSLICE_CONTROL__CTRL_CLK];
DIV_MODE_REG = ATTR[`BITSLICE_CONTROL__DIV_MODE];
EN_CLK_TO_EXT_NORTH_REG = ATTR[`BITSLICE_CONTROL__EN_CLK_TO_EXT_NORTH];
EN_CLK_TO_EXT_SOUTH_REG = ATTR[`BITSLICE_CONTROL__EN_CLK_TO_EXT_SOUTH];
EN_DYN_ODLY_MODE_REG = ATTR[`BITSLICE_CONTROL__EN_DYN_ODLY_MODE];
EN_OTHER_NCLK_REG = ATTR[`BITSLICE_CONTROL__EN_OTHER_NCLK];
EN_OTHER_PCLK_REG = ATTR[`BITSLICE_CONTROL__EN_OTHER_PCLK];
IDLY_VT_TRACK_REG = ATTR[`BITSLICE_CONTROL__IDLY_VT_TRACK];
INV_RXCLK_REG = ATTR[`BITSLICE_CONTROL__INV_RXCLK];
ODLY_VT_TRACK_REG = ATTR[`BITSLICE_CONTROL__ODLY_VT_TRACK];
QDLY_VT_TRACK_REG = ATTR[`BITSLICE_CONTROL__QDLY_VT_TRACK];
READ_IDLE_COUNT_REG = ATTR[`BITSLICE_CONTROL__READ_IDLE_COUNT];
REFCLK_SRC_REG = ATTR[`BITSLICE_CONTROL__REFCLK_SRC];
ROUNDING_FACTOR_REG = ATTR[`BITSLICE_CONTROL__ROUNDING_FACTOR];
RXGATE_EXTEND_REG = ATTR[`BITSLICE_CONTROL__RXGATE_EXTEND];
RX_CLK_PHASE_N_REG = ATTR[`BITSLICE_CONTROL__RX_CLK_PHASE_N];
RX_CLK_PHASE_P_REG = ATTR[`BITSLICE_CONTROL__RX_CLK_PHASE_P];
RX_GATING_REG = ATTR[`BITSLICE_CONTROL__RX_GATING];
SELF_CALIBRATE_REG = ATTR[`BITSLICE_CONTROL__SELF_CALIBRATE];
SERIAL_MODE_REG = ATTR[`BITSLICE_CONTROL__SERIAL_MODE];
SIM_SPEEDUP_REG = ATTR[`BITSLICE_CONTROL__SIM_SPEEDUP];
SIM_VERSION_REG = $bitstoreal(ATTR[`BITSLICE_CONTROL__SIM_VERSION]);
TX_GATING_REG = ATTR[`BITSLICE_CONTROL__TX_GATING];
end

// procedures to override, read attribute values

task write_attr;
  input  [`BITSLICE_CONTROL_ADDR_SZ-1:0] addr;
  input  [`BITSLICE_CONTROL_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`BITSLICE_CONTROL_DATA_SZ-1:0] read_attr;
  input  [`BITSLICE_CONTROL_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
    trig_attr = ~trig_attr;
  end
endtask
