`include "B_FIFO18E2_defines.vh"

reg [`FIFO18E2_DATA_SZ-1:0] ATTR [0:`FIFO18E2_ADDR_N-1];
reg [64:1] CASCADE_ORDER_REG = CASCADE_ORDER;
reg [88:1] CLOCK_DOMAINS_REG = CLOCK_DOMAINS;
reg [40:1] FIRST_WORD_FALL_THROUGH_REG = FIRST_WORD_FALL_THROUGH;
reg [35:0] INIT_REG = INIT;
reg IS_RDCLK_INVERTED_REG = IS_RDCLK_INVERTED;
reg IS_RDEN_INVERTED_REG = IS_RDEN_INVERTED;
reg IS_RSTREG_INVERTED_REG = IS_RSTREG_INVERTED;
reg IS_RST_INVERTED_REG = IS_RST_INVERTED;
reg IS_WRCLK_INVERTED_REG = IS_WRCLK_INVERTED;
reg IS_WREN_INVERTED_REG = IS_WREN_INVERTED;
reg [12:0] PROG_EMPTY_THRESH_REG = PROG_EMPTY_THRESH;
reg [12:0] PROG_FULL_THRESH_REG = PROG_FULL_THRESH;
reg [144:1] RDCOUNT_TYPE_REG = RDCOUNT_TYPE;
reg [5:0] READ_WIDTH_REG = READ_WIDTH;
reg [96:1] REGISTER_MODE_REG = REGISTER_MODE;
reg [48:1] RSTREG_PRIORITY_REG = RSTREG_PRIORITY;
reg [40:1] SLEEP_ASYNC_REG = SLEEP_ASYNC;
reg [35:0] SRVAL_REG = SRVAL;
reg [144:1] WRCOUNT_TYPE_REG = WRCOUNT_TYPE;
reg [5:0] WRITE_WIDTH_REG = WRITE_WIDTH;

initial begin
  ATTR[`FIFO18E2__CASCADE_ORDER] = CASCADE_ORDER;
  ATTR[`FIFO18E2__CLOCK_DOMAINS] = CLOCK_DOMAINS;
  ATTR[`FIFO18E2__FIRST_WORD_FALL_THROUGH] = FIRST_WORD_FALL_THROUGH;
  ATTR[`FIFO18E2__INIT] = INIT;
  ATTR[`FIFO18E2__IS_RDCLK_INVERTED] = IS_RDCLK_INVERTED;
  ATTR[`FIFO18E2__IS_RDEN_INVERTED] = IS_RDEN_INVERTED;
  ATTR[`FIFO18E2__IS_RSTREG_INVERTED] = IS_RSTREG_INVERTED;
  ATTR[`FIFO18E2__IS_RST_INVERTED] = IS_RST_INVERTED;
  ATTR[`FIFO18E2__IS_WRCLK_INVERTED] = IS_WRCLK_INVERTED;
  ATTR[`FIFO18E2__IS_WREN_INVERTED] = IS_WREN_INVERTED;
  ATTR[`FIFO18E2__PROG_EMPTY_THRESH] = PROG_EMPTY_THRESH;
  ATTR[`FIFO18E2__PROG_FULL_THRESH] = PROG_FULL_THRESH;
  ATTR[`FIFO18E2__RDCOUNT_TYPE] = RDCOUNT_TYPE;
  ATTR[`FIFO18E2__READ_WIDTH] = READ_WIDTH;
  ATTR[`FIFO18E2__REGISTER_MODE] = REGISTER_MODE;
  ATTR[`FIFO18E2__RSTREG_PRIORITY] = RSTREG_PRIORITY;
  ATTR[`FIFO18E2__SLEEP_ASYNC] = SLEEP_ASYNC;
  ATTR[`FIFO18E2__SRVAL] = SRVAL;
  ATTR[`FIFO18E2__WRCOUNT_TYPE] = WRCOUNT_TYPE;
  ATTR[`FIFO18E2__WRITE_WIDTH] = WRITE_WIDTH;
end

always @(posedge trig_attr) begin
  CASCADE_ORDER_REG = ATTR[`FIFO18E2__CASCADE_ORDER];
  CLOCK_DOMAINS_REG = ATTR[`FIFO18E2__CLOCK_DOMAINS];
  FIRST_WORD_FALL_THROUGH_REG = ATTR[`FIFO18E2__FIRST_WORD_FALL_THROUGH];
  INIT_REG = ATTR[`FIFO18E2__INIT];
  IS_RDCLK_INVERTED_REG = ATTR[`FIFO18E2__IS_RDCLK_INVERTED];
  IS_RDEN_INVERTED_REG = ATTR[`FIFO18E2__IS_RDEN_INVERTED];
  IS_RSTREG_INVERTED_REG = ATTR[`FIFO18E2__IS_RSTREG_INVERTED];
  IS_RST_INVERTED_REG = ATTR[`FIFO18E2__IS_RST_INVERTED];
  IS_WRCLK_INVERTED_REG = ATTR[`FIFO18E2__IS_WRCLK_INVERTED];
  IS_WREN_INVERTED_REG = ATTR[`FIFO18E2__IS_WREN_INVERTED];
  PROG_EMPTY_THRESH_REG = ATTR[`FIFO18E2__PROG_EMPTY_THRESH];
  PROG_FULL_THRESH_REG = ATTR[`FIFO18E2__PROG_FULL_THRESH];
  RDCOUNT_TYPE_REG = ATTR[`FIFO18E2__RDCOUNT_TYPE];
  READ_WIDTH_REG = ATTR[`FIFO18E2__READ_WIDTH];
  REGISTER_MODE_REG = ATTR[`FIFO18E2__REGISTER_MODE];
  RSTREG_PRIORITY_REG = ATTR[`FIFO18E2__RSTREG_PRIORITY];
  SLEEP_ASYNC_REG = ATTR[`FIFO18E2__SLEEP_ASYNC];
  SRVAL_REG = ATTR[`FIFO18E2__SRVAL];
  WRCOUNT_TYPE_REG = ATTR[`FIFO18E2__WRCOUNT_TYPE];
  WRITE_WIDTH_REG = ATTR[`FIFO18E2__WRITE_WIDTH];
end

// procedures to override, read attribute values

task write_attr;
  input  [`FIFO18E2_ADDR_SZ-1:0] addr;
  input  [`FIFO18E2_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
  end
endtask

function [`FIFO18E2_DATA_SZ-1:0] read_attr;
  input  [`FIFO18E2_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
    trig_attr = 1'b1;
    #100;
    trig_attr = 1'b0;
  end
endtask
