`include "B_ILKN_defines.vh"

reg [`ILKN_DATA_SZ-1:0] ATTR [0:`ILKN_ADDR_N-1];
  reg [40:1] BYPASS_REG = BYPASS;
  reg [1:0] CTL_RX_BURSTMAX_REG = CTL_RX_BURSTMAX;
  reg [1:0] CTL_RX_CHAN_EXT_REG = CTL_RX_CHAN_EXT;
  reg [3:0] CTL_RX_LAST_LANE_REG = CTL_RX_LAST_LANE;
  reg [15:0] CTL_RX_MFRAMELEN_MINUS1_REG = CTL_RX_MFRAMELEN_MINUS1;
  reg [40:1] CTL_RX_PACKET_MODE_REG = CTL_RX_PACKET_MODE;
  reg [2:0] CTL_RX_RETRANS_MULT_REG = CTL_RX_RETRANS_MULT;
  reg [3:0] CTL_RX_RETRANS_RETRY_REG = CTL_RX_RETRANS_RETRY;
  reg [15:0] CTL_RX_RETRANS_TIMER1_REG = CTL_RX_RETRANS_TIMER1;
  reg [15:0] CTL_RX_RETRANS_TIMER2_REG = CTL_RX_RETRANS_TIMER2;
  reg [11:0] CTL_RX_RETRANS_WDOG_REG = CTL_RX_RETRANS_WDOG;
  reg [7:0] CTL_RX_RETRANS_WRAP_TIMER_REG = CTL_RX_RETRANS_WRAP_TIMER;
  reg [40:1] CTL_TEST_MODE_PIN_CHAR_REG = CTL_TEST_MODE_PIN_CHAR;
  reg [1:0] CTL_TX_BURSTMAX_REG = CTL_TX_BURSTMAX;
  reg [2:0] CTL_TX_BURSTSHORT_REG = CTL_TX_BURSTSHORT;
  reg [1:0] CTL_TX_CHAN_EXT_REG = CTL_TX_CHAN_EXT;
  reg [40:1] CTL_TX_DISABLE_SKIPWORD_REG = CTL_TX_DISABLE_SKIPWORD;
  reg [6:0] CTL_TX_FC_CALLEN_REG = CTL_TX_FC_CALLEN;
  reg [3:0] CTL_TX_LAST_LANE_REG = CTL_TX_LAST_LANE;
  reg [15:0] CTL_TX_MFRAMELEN_MINUS1_REG = CTL_TX_MFRAMELEN_MINUS1;
  reg [13:0] CTL_TX_RETRANS_DEPTH_REG = CTL_TX_RETRANS_DEPTH;
  reg [2:0] CTL_TX_RETRANS_MULT_REG = CTL_TX_RETRANS_MULT;
  reg [1:0] CTL_TX_RETRANS_RAM_BANKS_REG = CTL_TX_RETRANS_RAM_BANKS;
  reg [40:1] MODE_REG = MODE;
  reg [40:1] TEST_MODE_PIN_CHAR_REG = TEST_MODE_PIN_CHAR;

initial begin
    ATTR[`ILKN__BYPASS] = BYPASS;
    ATTR[`ILKN__CTL_RX_BURSTMAX] = CTL_RX_BURSTMAX;
    ATTR[`ILKN__CTL_RX_CHAN_EXT] = CTL_RX_CHAN_EXT;
    ATTR[`ILKN__CTL_RX_LAST_LANE] = CTL_RX_LAST_LANE;
    ATTR[`ILKN__CTL_RX_MFRAMELEN_MINUS1] = CTL_RX_MFRAMELEN_MINUS1;
    ATTR[`ILKN__CTL_RX_PACKET_MODE] = CTL_RX_PACKET_MODE;
    ATTR[`ILKN__CTL_RX_RETRANS_MULT] = CTL_RX_RETRANS_MULT;
    ATTR[`ILKN__CTL_RX_RETRANS_RETRY] = CTL_RX_RETRANS_RETRY;
    ATTR[`ILKN__CTL_RX_RETRANS_TIMER1] = CTL_RX_RETRANS_TIMER1;
    ATTR[`ILKN__CTL_RX_RETRANS_TIMER2] = CTL_RX_RETRANS_TIMER2;
    ATTR[`ILKN__CTL_RX_RETRANS_WDOG] = CTL_RX_RETRANS_WDOG;
    ATTR[`ILKN__CTL_RX_RETRANS_WRAP_TIMER] = CTL_RX_RETRANS_WRAP_TIMER;
    ATTR[`ILKN__CTL_TEST_MODE_PIN_CHAR] = CTL_TEST_MODE_PIN_CHAR;
    ATTR[`ILKN__CTL_TX_BURSTMAX] = CTL_TX_BURSTMAX;
    ATTR[`ILKN__CTL_TX_BURSTSHORT] = CTL_TX_BURSTSHORT;
    ATTR[`ILKN__CTL_TX_CHAN_EXT] = CTL_TX_CHAN_EXT;
    ATTR[`ILKN__CTL_TX_DISABLE_SKIPWORD] = CTL_TX_DISABLE_SKIPWORD;
    ATTR[`ILKN__CTL_TX_FC_CALLEN] = CTL_TX_FC_CALLEN;
    ATTR[`ILKN__CTL_TX_LAST_LANE] = CTL_TX_LAST_LANE;
    ATTR[`ILKN__CTL_TX_MFRAMELEN_MINUS1] = CTL_TX_MFRAMELEN_MINUS1;
    ATTR[`ILKN__CTL_TX_RETRANS_DEPTH] = CTL_TX_RETRANS_DEPTH;
    ATTR[`ILKN__CTL_TX_RETRANS_MULT] = CTL_TX_RETRANS_MULT;
    ATTR[`ILKN__CTL_TX_RETRANS_RAM_BANKS] = CTL_TX_RETRANS_RAM_BANKS;
    ATTR[`ILKN__MODE] = MODE;
    ATTR[`ILKN__TEST_MODE_PIN_CHAR] = TEST_MODE_PIN_CHAR;
end

always @(trig_attr) begin
    BYPASS_REG = ATTR[`ILKN__BYPASS];
    CTL_RX_BURSTMAX_REG = ATTR[`ILKN__CTL_RX_BURSTMAX];
    CTL_RX_CHAN_EXT_REG = ATTR[`ILKN__CTL_RX_CHAN_EXT];
    CTL_RX_LAST_LANE_REG = ATTR[`ILKN__CTL_RX_LAST_LANE];
    CTL_RX_MFRAMELEN_MINUS1_REG = ATTR[`ILKN__CTL_RX_MFRAMELEN_MINUS1];
    CTL_RX_PACKET_MODE_REG = ATTR[`ILKN__CTL_RX_PACKET_MODE];
    CTL_RX_RETRANS_MULT_REG = ATTR[`ILKN__CTL_RX_RETRANS_MULT];
    CTL_RX_RETRANS_RETRY_REG = ATTR[`ILKN__CTL_RX_RETRANS_RETRY];
    CTL_RX_RETRANS_TIMER1_REG = ATTR[`ILKN__CTL_RX_RETRANS_TIMER1];
    CTL_RX_RETRANS_TIMER2_REG = ATTR[`ILKN__CTL_RX_RETRANS_TIMER2];
    CTL_RX_RETRANS_WDOG_REG = ATTR[`ILKN__CTL_RX_RETRANS_WDOG];
    CTL_RX_RETRANS_WRAP_TIMER_REG = ATTR[`ILKN__CTL_RX_RETRANS_WRAP_TIMER];
    CTL_TEST_MODE_PIN_CHAR_REG = ATTR[`ILKN__CTL_TEST_MODE_PIN_CHAR];
    CTL_TX_BURSTMAX_REG = ATTR[`ILKN__CTL_TX_BURSTMAX];
    CTL_TX_BURSTSHORT_REG = ATTR[`ILKN__CTL_TX_BURSTSHORT];
    CTL_TX_CHAN_EXT_REG = ATTR[`ILKN__CTL_TX_CHAN_EXT];
    CTL_TX_DISABLE_SKIPWORD_REG = ATTR[`ILKN__CTL_TX_DISABLE_SKIPWORD];
    CTL_TX_FC_CALLEN_REG = ATTR[`ILKN__CTL_TX_FC_CALLEN];
    CTL_TX_LAST_LANE_REG = ATTR[`ILKN__CTL_TX_LAST_LANE];
    CTL_TX_MFRAMELEN_MINUS1_REG = ATTR[`ILKN__CTL_TX_MFRAMELEN_MINUS1];
    CTL_TX_RETRANS_DEPTH_REG = ATTR[`ILKN__CTL_TX_RETRANS_DEPTH];
    CTL_TX_RETRANS_MULT_REG = ATTR[`ILKN__CTL_TX_RETRANS_MULT];
    CTL_TX_RETRANS_RAM_BANKS_REG = ATTR[`ILKN__CTL_TX_RETRANS_RAM_BANKS];
    MODE_REG = ATTR[`ILKN__MODE];
    TEST_MODE_PIN_CHAR_REG = ATTR[`ILKN__TEST_MODE_PIN_CHAR];
end

// procedures to override, read attribute values

task write_attr;
  input  [`ILKN_ADDR_SZ-1:0] addr;
  input  [`ILKN_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`ILKN_DATA_SZ-1:0] read_attr;
  input  [`ILKN_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
    trig_attr = ~trig_attr;
  end
endtask
