`include "B_MMCME3_ADV_defines.vh"

reg [`MMCME3_ADV_DATA_SZ-1:0] ATTR [0:`MMCME3_ADV_ADDR_N-1];
reg [72:1] BANDWIDTH_REG = BANDWIDTH;
real CLKFBOUT_MULT_F_REG = CLKFBOUT_MULT_F;
real CLKFBOUT_PHASE_REG = CLKFBOUT_PHASE;
reg [40:1] CLKFBOUT_USE_FINE_PS_REG = CLKFBOUT_USE_FINE_PS;
real CLKIN1_PERIOD_REG = CLKIN1_PERIOD;
real CLKIN2_PERIOD_REG = CLKIN2_PERIOD;
real CLKIN_FREQ_MAX_REG = CLKIN_FREQ_MAX;
real CLKIN_FREQ_MIN_REG = CLKIN_FREQ_MIN;
real CLKOUT0_DIVIDE_F_REG = CLKOUT0_DIVIDE_F;
real CLKOUT0_DUTY_CYCLE_REG = CLKOUT0_DUTY_CYCLE;
real CLKOUT0_PHASE_REG = CLKOUT0_PHASE;
reg [40:1] CLKOUT0_USE_FINE_PS_REG = CLKOUT0_USE_FINE_PS;
reg [7:0] CLKOUT1_DIVIDE_REG = CLKOUT1_DIVIDE;
real CLKOUT1_DUTY_CYCLE_REG = CLKOUT1_DUTY_CYCLE;
real CLKOUT1_PHASE_REG = CLKOUT1_PHASE;
reg [40:1] CLKOUT1_USE_FINE_PS_REG = CLKOUT1_USE_FINE_PS;
reg [7:0] CLKOUT2_DIVIDE_REG = CLKOUT2_DIVIDE;
real CLKOUT2_DUTY_CYCLE_REG = CLKOUT2_DUTY_CYCLE;
real CLKOUT2_PHASE_REG = CLKOUT2_PHASE;
reg [40:1] CLKOUT2_USE_FINE_PS_REG = CLKOUT2_USE_FINE_PS;
reg [7:0] CLKOUT3_DIVIDE_REG = CLKOUT3_DIVIDE;
real CLKOUT3_DUTY_CYCLE_REG = CLKOUT3_DUTY_CYCLE;
real CLKOUT3_PHASE_REG = CLKOUT3_PHASE;
reg [40:1] CLKOUT3_USE_FINE_PS_REG = CLKOUT3_USE_FINE_PS;
reg [40:1] CLKOUT4_CASCADE_REG = CLKOUT4_CASCADE;
reg [7:0] CLKOUT4_DIVIDE_REG = CLKOUT4_DIVIDE;
real CLKOUT4_DUTY_CYCLE_REG = CLKOUT4_DUTY_CYCLE;
real CLKOUT4_PHASE_REG = CLKOUT4_PHASE;
reg [40:1] CLKOUT4_USE_FINE_PS_REG = CLKOUT4_USE_FINE_PS;
reg [7:0] CLKOUT5_DIVIDE_REG = CLKOUT5_DIVIDE;
real CLKOUT5_DUTY_CYCLE_REG = CLKOUT5_DUTY_CYCLE;
real CLKOUT5_PHASE_REG = CLKOUT5_PHASE;
reg [40:1] CLKOUT5_USE_FINE_PS_REG = CLKOUT5_USE_FINE_PS;
reg [7:0] CLKOUT6_DIVIDE_REG = CLKOUT6_DIVIDE;
real CLKOUT6_DUTY_CYCLE_REG = CLKOUT6_DUTY_CYCLE;
real CLKOUT6_PHASE_REG = CLKOUT6_PHASE;
reg [40:1] CLKOUT6_USE_FINE_PS_REG = CLKOUT6_USE_FINE_PS;
real CLKPFD_FREQ_MAX_REG = CLKPFD_FREQ_MAX;
real CLKPFD_FREQ_MIN_REG = CLKPFD_FREQ_MIN;
reg [64:1] COMPENSATION_REG = COMPENSATION;
reg [6:0] DIVCLK_DIVIDE_REG = DIVCLK_DIVIDE;
reg IS_CLKFBIN_INVERTED_REG = IS_CLKFBIN_INVERTED;
reg IS_CLKIN1_INVERTED_REG = IS_CLKIN1_INVERTED;
reg IS_CLKIN2_INVERTED_REG = IS_CLKIN2_INVERTED;
reg IS_CLKINSEL_INVERTED_REG = IS_CLKINSEL_INVERTED;
reg IS_PSEN_INVERTED_REG = IS_PSEN_INVERTED;
reg IS_PSINCDEC_INVERTED_REG = IS_PSINCDEC_INVERTED;
reg IS_PWRDWN_INVERTED_REG = IS_PWRDWN_INVERTED;
reg IS_RST_INVERTED_REG = IS_RST_INVERTED;
real REF_JITTER1_REG = REF_JITTER1;
real REF_JITTER2_REG = REF_JITTER2;
reg [40:1] SS_EN_REG = SS_EN;
reg [88:1] SS_MODE_REG = SS_MODE;
reg [15:0] SS_MOD_PERIOD_REG = SS_MOD_PERIOD;
reg [40:1] STARTUP_WAIT_REG = STARTUP_WAIT;
real VCOCLK_FREQ_MAX_REG = VCOCLK_FREQ_MAX;
real VCOCLK_FREQ_MIN_REG = VCOCLK_FREQ_MIN;

initial begin
  ATTR[`MMCME3_ADV__BANDWIDTH] = BANDWIDTH;
  ATTR[`MMCME3_ADV__CLKFBOUT_MULT_F] = $realtobits(CLKFBOUT_MULT_F);
  ATTR[`MMCME3_ADV__CLKFBOUT_PHASE] = $realtobits(CLKFBOUT_PHASE);
  ATTR[`MMCME3_ADV__CLKFBOUT_USE_FINE_PS] = CLKFBOUT_USE_FINE_PS;
  ATTR[`MMCME3_ADV__CLKIN1_PERIOD] = $realtobits(CLKIN1_PERIOD);
  ATTR[`MMCME3_ADV__CLKIN2_PERIOD] = $realtobits(CLKIN2_PERIOD);
  ATTR[`MMCME3_ADV__CLKIN_FREQ_MAX] = $realtobits(CLKIN_FREQ_MAX);
  ATTR[`MMCME3_ADV__CLKIN_FREQ_MIN] = $realtobits(CLKIN_FREQ_MIN);
  ATTR[`MMCME3_ADV__CLKOUT0_DIVIDE_F] = $realtobits(CLKOUT0_DIVIDE_F);
  ATTR[`MMCME3_ADV__CLKOUT0_DUTY_CYCLE] = $realtobits(CLKOUT0_DUTY_CYCLE);
  ATTR[`MMCME3_ADV__CLKOUT0_PHASE] = $realtobits(CLKOUT0_PHASE);
  ATTR[`MMCME3_ADV__CLKOUT0_USE_FINE_PS] = CLKOUT0_USE_FINE_PS;
  ATTR[`MMCME3_ADV__CLKOUT1_DIVIDE] = CLKOUT1_DIVIDE;
  ATTR[`MMCME3_ADV__CLKOUT1_DUTY_CYCLE] = $realtobits(CLKOUT1_DUTY_CYCLE);
  ATTR[`MMCME3_ADV__CLKOUT1_PHASE] = $realtobits(CLKOUT1_PHASE);
  ATTR[`MMCME3_ADV__CLKOUT1_USE_FINE_PS] = CLKOUT1_USE_FINE_PS;
  ATTR[`MMCME3_ADV__CLKOUT2_DIVIDE] = CLKOUT2_DIVIDE;
  ATTR[`MMCME3_ADV__CLKOUT2_DUTY_CYCLE] = $realtobits(CLKOUT2_DUTY_CYCLE);
  ATTR[`MMCME3_ADV__CLKOUT2_PHASE] = $realtobits(CLKOUT2_PHASE);
  ATTR[`MMCME3_ADV__CLKOUT2_USE_FINE_PS] = CLKOUT2_USE_FINE_PS;
  ATTR[`MMCME3_ADV__CLKOUT3_DIVIDE] = CLKOUT3_DIVIDE;
  ATTR[`MMCME3_ADV__CLKOUT3_DUTY_CYCLE] = $realtobits(CLKOUT3_DUTY_CYCLE);
  ATTR[`MMCME3_ADV__CLKOUT3_PHASE] = $realtobits(CLKOUT3_PHASE);
  ATTR[`MMCME3_ADV__CLKOUT3_USE_FINE_PS] = CLKOUT3_USE_FINE_PS;
  ATTR[`MMCME3_ADV__CLKOUT4_CASCADE] = CLKOUT4_CASCADE;
  ATTR[`MMCME3_ADV__CLKOUT4_DIVIDE] = CLKOUT4_DIVIDE;
  ATTR[`MMCME3_ADV__CLKOUT4_DUTY_CYCLE] = $realtobits(CLKOUT4_DUTY_CYCLE);
  ATTR[`MMCME3_ADV__CLKOUT4_PHASE] = $realtobits(CLKOUT4_PHASE);
  ATTR[`MMCME3_ADV__CLKOUT4_USE_FINE_PS] = CLKOUT4_USE_FINE_PS;
  ATTR[`MMCME3_ADV__CLKOUT5_DIVIDE] = CLKOUT5_DIVIDE;
  ATTR[`MMCME3_ADV__CLKOUT5_DUTY_CYCLE] = $realtobits(CLKOUT5_DUTY_CYCLE);
  ATTR[`MMCME3_ADV__CLKOUT5_PHASE] = $realtobits(CLKOUT5_PHASE);
  ATTR[`MMCME3_ADV__CLKOUT5_USE_FINE_PS] = CLKOUT5_USE_FINE_PS;
  ATTR[`MMCME3_ADV__CLKOUT6_DIVIDE] = CLKOUT6_DIVIDE;
  ATTR[`MMCME3_ADV__CLKOUT6_DUTY_CYCLE] = $realtobits(CLKOUT6_DUTY_CYCLE);
  ATTR[`MMCME3_ADV__CLKOUT6_PHASE] = $realtobits(CLKOUT6_PHASE);
  ATTR[`MMCME3_ADV__CLKOUT6_USE_FINE_PS] = CLKOUT6_USE_FINE_PS;
  ATTR[`MMCME3_ADV__CLKPFD_FREQ_MAX] = $realtobits(CLKPFD_FREQ_MAX);
  ATTR[`MMCME3_ADV__CLKPFD_FREQ_MIN] = $realtobits(CLKPFD_FREQ_MIN);
  ATTR[`MMCME3_ADV__COMPENSATION] = COMPENSATION;
  ATTR[`MMCME3_ADV__DIVCLK_DIVIDE] = DIVCLK_DIVIDE;
  ATTR[`MMCME3_ADV__IS_CLKFBIN_INVERTED] = IS_CLKFBIN_INVERTED;
  ATTR[`MMCME3_ADV__IS_CLKIN1_INVERTED] = IS_CLKIN1_INVERTED;
  ATTR[`MMCME3_ADV__IS_CLKIN2_INVERTED] = IS_CLKIN2_INVERTED;
  ATTR[`MMCME3_ADV__IS_CLKINSEL_INVERTED] = IS_CLKINSEL_INVERTED;
  ATTR[`MMCME3_ADV__IS_PSEN_INVERTED] = IS_PSEN_INVERTED;
  ATTR[`MMCME3_ADV__IS_PSINCDEC_INVERTED] = IS_PSINCDEC_INVERTED;
  ATTR[`MMCME3_ADV__IS_PWRDWN_INVERTED] = IS_PWRDWN_INVERTED;
  ATTR[`MMCME3_ADV__IS_RST_INVERTED] = IS_RST_INVERTED;
  ATTR[`MMCME3_ADV__REF_JITTER1] = $realtobits(REF_JITTER1);
  ATTR[`MMCME3_ADV__REF_JITTER2] = $realtobits(REF_JITTER2);
  ATTR[`MMCME3_ADV__SS_EN] = SS_EN;
  ATTR[`MMCME3_ADV__SS_MODE] = SS_MODE;
  ATTR[`MMCME3_ADV__SS_MOD_PERIOD] = SS_MOD_PERIOD;
  ATTR[`MMCME3_ADV__STARTUP_WAIT] = STARTUP_WAIT;
  ATTR[`MMCME3_ADV__VCOCLK_FREQ_MAX] = $realtobits(VCOCLK_FREQ_MAX);
  ATTR[`MMCME3_ADV__VCOCLK_FREQ_MIN] = $realtobits(VCOCLK_FREQ_MIN);
end

always @(trig_attr) begin
  BANDWIDTH_REG = ATTR[`MMCME3_ADV__BANDWIDTH];
  CLKFBOUT_MULT_F_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKFBOUT_MULT_F]);
  CLKFBOUT_PHASE_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKFBOUT_PHASE]);
  CLKFBOUT_USE_FINE_PS_REG = ATTR[`MMCME3_ADV__CLKFBOUT_USE_FINE_PS];
  CLKIN1_PERIOD_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKIN1_PERIOD]);
  CLKIN2_PERIOD_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKIN2_PERIOD]);
  CLKIN_FREQ_MAX_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKIN_FREQ_MAX]);
  CLKIN_FREQ_MIN_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKIN_FREQ_MIN]);
  CLKOUT0_DIVIDE_F_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKOUT0_DIVIDE_F]);
  CLKOUT0_DUTY_CYCLE_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKOUT0_DUTY_CYCLE]);
  CLKOUT0_PHASE_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKOUT0_PHASE]);
  CLKOUT0_USE_FINE_PS_REG = ATTR[`MMCME3_ADV__CLKOUT0_USE_FINE_PS];
  CLKOUT1_DIVIDE_REG = ATTR[`MMCME3_ADV__CLKOUT1_DIVIDE];
  CLKOUT1_DUTY_CYCLE_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKOUT1_DUTY_CYCLE]);
  CLKOUT1_PHASE_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKOUT1_PHASE]);
  CLKOUT1_USE_FINE_PS_REG = ATTR[`MMCME3_ADV__CLKOUT1_USE_FINE_PS];
  CLKOUT2_DIVIDE_REG = ATTR[`MMCME3_ADV__CLKOUT2_DIVIDE];
  CLKOUT2_DUTY_CYCLE_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKOUT2_DUTY_CYCLE]);
  CLKOUT2_PHASE_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKOUT2_PHASE]);
  CLKOUT2_USE_FINE_PS_REG = ATTR[`MMCME3_ADV__CLKOUT2_USE_FINE_PS];
  CLKOUT3_DIVIDE_REG = ATTR[`MMCME3_ADV__CLKOUT3_DIVIDE];
  CLKOUT3_DUTY_CYCLE_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKOUT3_DUTY_CYCLE]);
  CLKOUT3_PHASE_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKOUT3_PHASE]);
  CLKOUT3_USE_FINE_PS_REG = ATTR[`MMCME3_ADV__CLKOUT3_USE_FINE_PS];
  CLKOUT4_CASCADE_REG = ATTR[`MMCME3_ADV__CLKOUT4_CASCADE];
  CLKOUT4_DIVIDE_REG = ATTR[`MMCME3_ADV__CLKOUT4_DIVIDE];
  CLKOUT4_DUTY_CYCLE_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKOUT4_DUTY_CYCLE]);
  CLKOUT4_PHASE_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKOUT4_PHASE]);
  CLKOUT4_USE_FINE_PS_REG = ATTR[`MMCME3_ADV__CLKOUT4_USE_FINE_PS];
  CLKOUT5_DIVIDE_REG = ATTR[`MMCME3_ADV__CLKOUT5_DIVIDE];
  CLKOUT5_DUTY_CYCLE_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKOUT5_DUTY_CYCLE]);
  CLKOUT5_PHASE_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKOUT5_PHASE]);
  CLKOUT5_USE_FINE_PS_REG = ATTR[`MMCME3_ADV__CLKOUT5_USE_FINE_PS];
  CLKOUT6_DIVIDE_REG = ATTR[`MMCME3_ADV__CLKOUT6_DIVIDE];
  CLKOUT6_DUTY_CYCLE_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKOUT6_DUTY_CYCLE]);
  CLKOUT6_PHASE_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKOUT6_PHASE]);
  CLKOUT6_USE_FINE_PS_REG = ATTR[`MMCME3_ADV__CLKOUT6_USE_FINE_PS];
  CLKPFD_FREQ_MAX_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKPFD_FREQ_MAX]);
  CLKPFD_FREQ_MIN_REG = $bitstoreal(ATTR[`MMCME3_ADV__CLKPFD_FREQ_MIN]);
  COMPENSATION_REG = ATTR[`MMCME3_ADV__COMPENSATION];
  DIVCLK_DIVIDE_REG = ATTR[`MMCME3_ADV__DIVCLK_DIVIDE];
  IS_CLKFBIN_INVERTED_REG = ATTR[`MMCME3_ADV__IS_CLKFBIN_INVERTED];
  IS_CLKIN1_INVERTED_REG = ATTR[`MMCME3_ADV__IS_CLKIN1_INVERTED];
  IS_CLKIN2_INVERTED_REG = ATTR[`MMCME3_ADV__IS_CLKIN2_INVERTED];
  IS_CLKINSEL_INVERTED_REG = ATTR[`MMCME3_ADV__IS_CLKINSEL_INVERTED];
  IS_PSEN_INVERTED_REG = ATTR[`MMCME3_ADV__IS_PSEN_INVERTED];
  IS_PSINCDEC_INVERTED_REG = ATTR[`MMCME3_ADV__IS_PSINCDEC_INVERTED];
  IS_PWRDWN_INVERTED_REG = ATTR[`MMCME3_ADV__IS_PWRDWN_INVERTED];
  IS_RST_INVERTED_REG = ATTR[`MMCME3_ADV__IS_RST_INVERTED];
  REF_JITTER1_REG = $bitstoreal(ATTR[`MMCME3_ADV__REF_JITTER1]);
  REF_JITTER2_REG = $bitstoreal(ATTR[`MMCME3_ADV__REF_JITTER2]);
  SS_EN_REG = ATTR[`MMCME3_ADV__SS_EN];
  SS_MODE_REG = ATTR[`MMCME3_ADV__SS_MODE];
  SS_MOD_PERIOD_REG = ATTR[`MMCME3_ADV__SS_MOD_PERIOD];
  STARTUP_WAIT_REG = ATTR[`MMCME3_ADV__STARTUP_WAIT];
  VCOCLK_FREQ_MAX_REG = $bitstoreal(ATTR[`MMCME3_ADV__VCOCLK_FREQ_MAX]);
  VCOCLK_FREQ_MIN_REG = $bitstoreal(ATTR[`MMCME3_ADV__VCOCLK_FREQ_MIN]);
end

// procedures to override, read attribute values

task write_attr;
  input  [`MMCME3_ADV_ADDR_SZ-1:0] addr;
  input  [`MMCME3_ADV_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`MMCME3_ADV_DATA_SZ-1:0] read_attr;
  input  [`MMCME3_ADV_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
    trig_attr = ~trig_attr;
  end
endtask
