`include "B_PLLE3_ADV_defines.vh"

reg [`PLLE3_ADV_DATA_SZ-1:0] ATTR [0:`PLLE3_ADV_ADDR_N-1];
reg [4:0] CLKFBOUT_MULT_REG = CLKFBOUT_MULT;
real CLKFBOUT_PHASE_REG = CLKFBOUT_PHASE;
real CLKIN_FREQ_MAX_REG = CLKIN_FREQ_MAX;
real CLKIN_FREQ_MIN_REG = CLKIN_FREQ_MIN;
real CLKIN_PERIOD_REG = CLKIN_PERIOD;
reg [7:0] CLKOUT0_DIVIDE_REG = CLKOUT0_DIVIDE;
real CLKOUT0_DUTY_CYCLE_REG = CLKOUT0_DUTY_CYCLE;
real CLKOUT0_PHASE_REG = CLKOUT0_PHASE;
reg [7:0] CLKOUT1_DIVIDE_REG = CLKOUT1_DIVIDE;
real CLKOUT1_DUTY_CYCLE_REG = CLKOUT1_DUTY_CYCLE;
real CLKOUT1_PHASE_REG = CLKOUT1_PHASE;
reg [64:1] CLKOUTPHY_MODE_REG = CLKOUTPHY_MODE;
real CLKPFD_FREQ_MAX_REG = CLKPFD_FREQ_MAX;
real CLKPFD_FREQ_MIN_REG = CLKPFD_FREQ_MIN;
reg [64:1] COMPENSATION_REG = COMPENSATION;
reg [3:0] DIVCLK_DIVIDE_REG = DIVCLK_DIVIDE;
reg IS_CLKFBIN_INVERTED_REG = IS_CLKFBIN_INVERTED;
reg IS_CLKIN_INVERTED_REG = IS_CLKIN_INVERTED;
reg IS_PWRDWN_INVERTED_REG = IS_PWRDWN_INVERTED;
reg IS_RST_INVERTED_REG = IS_RST_INVERTED;
real REF_JITTER_REG = REF_JITTER;
reg [40:1] STARTUP_WAIT_REG = STARTUP_WAIT;
real VCOCLK_FREQ_MAX_REG = VCOCLK_FREQ_MAX;
real VCOCLK_FREQ_MIN_REG = VCOCLK_FREQ_MIN;

initial begin
  ATTR[`PLLE3_ADV__CLKFBOUT_MULT] = CLKFBOUT_MULT;
  ATTR[`PLLE3_ADV__CLKFBOUT_PHASE] = $realtobits(CLKFBOUT_PHASE);
  ATTR[`PLLE3_ADV__CLKIN_FREQ_MAX] = $realtobits(CLKIN_FREQ_MAX);
  ATTR[`PLLE3_ADV__CLKIN_FREQ_MIN] = $realtobits(CLKIN_FREQ_MIN);
  ATTR[`PLLE3_ADV__CLKIN_PERIOD] = $realtobits(CLKIN_PERIOD);
  ATTR[`PLLE3_ADV__CLKOUT0_DIVIDE] = CLKOUT0_DIVIDE;
  ATTR[`PLLE3_ADV__CLKOUT0_DUTY_CYCLE] = $realtobits(CLKOUT0_DUTY_CYCLE);
  ATTR[`PLLE3_ADV__CLKOUT0_PHASE] = $realtobits(CLKOUT0_PHASE);
  ATTR[`PLLE3_ADV__CLKOUT1_DIVIDE] = CLKOUT1_DIVIDE;
  ATTR[`PLLE3_ADV__CLKOUT1_DUTY_CYCLE] = $realtobits(CLKOUT1_DUTY_CYCLE);
  ATTR[`PLLE3_ADV__CLKOUT1_PHASE] = $realtobits(CLKOUT1_PHASE);
  ATTR[`PLLE3_ADV__CLKOUTPHY_MODE] = CLKOUTPHY_MODE;
  ATTR[`PLLE3_ADV__CLKPFD_FREQ_MAX] = $realtobits(CLKPFD_FREQ_MAX);
  ATTR[`PLLE3_ADV__CLKPFD_FREQ_MIN] = $realtobits(CLKPFD_FREQ_MIN);
  ATTR[`PLLE3_ADV__COMPENSATION] = COMPENSATION;
  ATTR[`PLLE3_ADV__DIVCLK_DIVIDE] = DIVCLK_DIVIDE;
  ATTR[`PLLE3_ADV__IS_CLKFBIN_INVERTED] = IS_CLKFBIN_INVERTED;
  ATTR[`PLLE3_ADV__IS_CLKIN_INVERTED] = IS_CLKIN_INVERTED;
  ATTR[`PLLE3_ADV__IS_PWRDWN_INVERTED] = IS_PWRDWN_INVERTED;
  ATTR[`PLLE3_ADV__IS_RST_INVERTED] = IS_RST_INVERTED;
  ATTR[`PLLE3_ADV__REF_JITTER] = $realtobits(REF_JITTER);
  ATTR[`PLLE3_ADV__STARTUP_WAIT] = STARTUP_WAIT;
  ATTR[`PLLE3_ADV__VCOCLK_FREQ_MAX] = $realtobits(VCOCLK_FREQ_MAX);
  ATTR[`PLLE3_ADV__VCOCLK_FREQ_MIN] = $realtobits(VCOCLK_FREQ_MIN);
end

always @(trig_attr) begin
  CLKFBOUT_MULT_REG = ATTR[`PLLE3_ADV__CLKFBOUT_MULT];
  CLKFBOUT_PHASE_REG = $bitstoreal(ATTR[`PLLE3_ADV__CLKFBOUT_PHASE]);
  CLKIN_FREQ_MAX_REG = $bitstoreal(ATTR[`PLLE3_ADV__CLKIN_FREQ_MAX]);
  CLKIN_FREQ_MIN_REG = $bitstoreal(ATTR[`PLLE3_ADV__CLKIN_FREQ_MIN]);
  CLKIN_PERIOD_REG = $bitstoreal(ATTR[`PLLE3_ADV__CLKIN_PERIOD]);
  CLKOUT0_DIVIDE_REG = ATTR[`PLLE3_ADV__CLKOUT0_DIVIDE];
  CLKOUT0_DUTY_CYCLE_REG = $bitstoreal(ATTR[`PLLE3_ADV__CLKOUT0_DUTY_CYCLE]);
  CLKOUT0_PHASE_REG = $bitstoreal(ATTR[`PLLE3_ADV__CLKOUT0_PHASE]);
  CLKOUT1_DIVIDE_REG = ATTR[`PLLE3_ADV__CLKOUT1_DIVIDE];
  CLKOUT1_DUTY_CYCLE_REG = $bitstoreal(ATTR[`PLLE3_ADV__CLKOUT1_DUTY_CYCLE]);
  CLKOUT1_PHASE_REG = $bitstoreal(ATTR[`PLLE3_ADV__CLKOUT1_PHASE]);
  CLKOUTPHY_MODE_REG = ATTR[`PLLE3_ADV__CLKOUTPHY_MODE];
  CLKPFD_FREQ_MAX_REG = $bitstoreal(ATTR[`PLLE3_ADV__CLKPFD_FREQ_MAX]);
  CLKPFD_FREQ_MIN_REG = $bitstoreal(ATTR[`PLLE3_ADV__CLKPFD_FREQ_MIN]);
  COMPENSATION_REG = ATTR[`PLLE3_ADV__COMPENSATION];
  DIVCLK_DIVIDE_REG = ATTR[`PLLE3_ADV__DIVCLK_DIVIDE];
  IS_CLKFBIN_INVERTED_REG = ATTR[`PLLE3_ADV__IS_CLKFBIN_INVERTED];
  IS_CLKIN_INVERTED_REG = ATTR[`PLLE3_ADV__IS_CLKIN_INVERTED];
  IS_PWRDWN_INVERTED_REG = ATTR[`PLLE3_ADV__IS_PWRDWN_INVERTED];
  IS_RST_INVERTED_REG = ATTR[`PLLE3_ADV__IS_RST_INVERTED];
  REF_JITTER_REG = $bitstoreal(ATTR[`PLLE3_ADV__REF_JITTER]);
  STARTUP_WAIT_REG = ATTR[`PLLE3_ADV__STARTUP_WAIT];
  VCOCLK_FREQ_MAX_REG = $bitstoreal(ATTR[`PLLE3_ADV__VCOCLK_FREQ_MAX]);
  VCOCLK_FREQ_MIN_REG = $bitstoreal(ATTR[`PLLE3_ADV__VCOCLK_FREQ_MIN]);
end

// procedures to override, read attribute values

task write_attr;
  input  [`PLLE3_ADV_ADDR_SZ-1:0] addr;
  input  [`PLLE3_ADV_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`PLLE3_ADV_DATA_SZ-1:0] read_attr;
  input  [`PLLE3_ADV_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
    trig_attr = ~trig_attr;
  end
endtask
