`include "B_SYSMONE1_defines.vh"

reg trig_attr = 0;
reg [`SYSMONE1_DATA_SZ-1:0] ATTR [0:`SYSMONE1_ADDR_N-1];

initial begin

  ATTR[`SYSMONE1__INIT_4A]	= INIT_4A;
  ATTR[`SYSMONE1__INIT_4B]	= INIT_4B;
  ATTR[`SYSMONE1__INIT_4C]	= INIT_4C;
  ATTR[`SYSMONE1__INIT_4D]	= INIT_4D;
  ATTR[`SYSMONE1__INIT_4E]	= INIT_4E;
  ATTR[`SYSMONE1__INIT_4F]	= INIT_4F;
  ATTR[`SYSMONE1__INIT_5A]	= INIT_5A;
  ATTR[`SYSMONE1__INIT_5B]	= INIT_5B;
  ATTR[`SYSMONE1__INIT_5C]	= INIT_5C;
  ATTR[`SYSMONE1__INIT_5D]	= INIT_5D;
  ATTR[`SYSMONE1__INIT_5E]	= INIT_5E;
  ATTR[`SYSMONE1__INIT_5F]	= INIT_5F;
  ATTR[`SYSMONE1__INIT_6A]	= INIT_6A;
  ATTR[`SYSMONE1__INIT_6B]	= INIT_6B;
  ATTR[`SYSMONE1__INIT_6C]	= INIT_6C;
  ATTR[`SYSMONE1__INIT_6D]	= INIT_6D;
  ATTR[`SYSMONE1__INIT_6E]	= INIT_6E;
  ATTR[`SYSMONE1__INIT_6F]	= INIT_6F;
  ATTR[`SYSMONE1__INIT_7A]	= INIT_7A;
  ATTR[`SYSMONE1__INIT_7B]	= INIT_7B;
  ATTR[`SYSMONE1__INIT_7C]	= INIT_7C;
  ATTR[`SYSMONE1__INIT_7D]	= INIT_7D;
  ATTR[`SYSMONE1__INIT_7E]	= INIT_7E;
  ATTR[`SYSMONE1__INIT_7F]	= INIT_7F;
  ATTR[`SYSMONE1__INIT_40]	= INIT_40;
  ATTR[`SYSMONE1__INIT_41]	= INIT_41;
  ATTR[`SYSMONE1__INIT_42]	= INIT_42;
  ATTR[`SYSMONE1__INIT_43]	= INIT_43;
  ATTR[`SYSMONE1__INIT_44]	= INIT_44;
  ATTR[`SYSMONE1__INIT_45]	= INIT_45;
  ATTR[`SYSMONE1__INIT_46]	= INIT_46;
  ATTR[`SYSMONE1__INIT_47]	= INIT_47;
  ATTR[`SYSMONE1__INIT_48]	= INIT_48;
  ATTR[`SYSMONE1__INIT_49]	= INIT_49;
  ATTR[`SYSMONE1__INIT_50]	= INIT_50;
  ATTR[`SYSMONE1__INIT_51]	= INIT_51;
  ATTR[`SYSMONE1__INIT_52]	= INIT_52;
  ATTR[`SYSMONE1__INIT_53]	= INIT_53;
  ATTR[`SYSMONE1__INIT_54]	= INIT_54;
  ATTR[`SYSMONE1__INIT_55]	= INIT_55;
  ATTR[`SYSMONE1__INIT_56]	= INIT_56;
  ATTR[`SYSMONE1__INIT_57]	= INIT_57;
  ATTR[`SYSMONE1__INIT_58]	= INIT_58;
  ATTR[`SYSMONE1__INIT_59]	= INIT_59;
  ATTR[`SYSMONE1__INIT_60]	= INIT_60;
  ATTR[`SYSMONE1__INIT_61]	= INIT_61;
  ATTR[`SYSMONE1__INIT_62]	= INIT_62;
  ATTR[`SYSMONE1__INIT_63]	= INIT_63;
  ATTR[`SYSMONE1__INIT_64]	= INIT_64;
  ATTR[`SYSMONE1__INIT_65]	= INIT_65;
  ATTR[`SYSMONE1__INIT_66]	= INIT_66;
  ATTR[`SYSMONE1__INIT_67]	= INIT_67;
  ATTR[`SYSMONE1__INIT_68]	= INIT_68;
  ATTR[`SYSMONE1__INIT_69]	= INIT_69;
  ATTR[`SYSMONE1__INIT_70]	= INIT_70;
  ATTR[`SYSMONE1__INIT_71]	= INIT_71;
  ATTR[`SYSMONE1__INIT_72]	= INIT_72;
  ATTR[`SYSMONE1__INIT_73]	= INIT_73;
  ATTR[`SYSMONE1__INIT_74]	= INIT_74;
  ATTR[`SYSMONE1__INIT_75]	= INIT_75;
  ATTR[`SYSMONE1__INIT_76]	= INIT_76;
  ATTR[`SYSMONE1__INIT_77]	= INIT_77;
  ATTR[`SYSMONE1__INIT_78]	= INIT_78;
  ATTR[`SYSMONE1__INIT_79]	= INIT_79;
  ATTR[`SYSMONE1__IS_CONVSTCLK_INVERTED] = IS_CONVSTCLK_INVERTED;
  ATTR[`SYSMONE1__IS_DCLK_INVERTED] = IS_DCLK_INVERTED;
end

//initial begin
always @(trig_attr) begin

    INIT_40_reg <= ATTR[`SYSMONE1__INIT_40];
    INIT_41_reg <= ATTR[`SYSMONE1__INIT_41];
    INIT_42_reg <= ATTR[`SYSMONE1__INIT_42];
    INIT_43_reg <= ATTR[`SYSMONE1__INIT_43];
    INIT_44_reg <= ATTR[`SYSMONE1__INIT_44];
    INIT_45_reg <= ATTR[`SYSMONE1__INIT_45];
    INIT_46_reg <= ATTR[`SYSMONE1__INIT_46];
    INIT_47_reg <= ATTR[`SYSMONE1__INIT_47];
    INIT_48_reg <= ATTR[`SYSMONE1__INIT_48];
    INIT_49_reg <= ATTR[`SYSMONE1__INIT_49];
    INIT_4A_reg <= ATTR[`SYSMONE1__INIT_4A];
    INIT_4B_reg <= ATTR[`SYSMONE1__INIT_4B];
    INIT_4C_reg <= ATTR[`SYSMONE1__INIT_4C];
    INIT_4D_reg <= ATTR[`SYSMONE1__INIT_4D];
    INIT_4E_reg <= ATTR[`SYSMONE1__INIT_4E];
    INIT_4F_reg <= ATTR[`SYSMONE1__INIT_4F];
    INIT_50_reg <= ATTR[`SYSMONE1__INIT_50];
    INIT_51_reg <= ATTR[`SYSMONE1__INIT_51];
    INIT_52_reg <= ATTR[`SYSMONE1__INIT_52];
    INIT_53_reg <= ATTR[`SYSMONE1__INIT_53];
    INIT_54_reg <= ATTR[`SYSMONE1__INIT_54];
    INIT_55_reg <= ATTR[`SYSMONE1__INIT_55];
    INIT_56_reg <= ATTR[`SYSMONE1__INIT_56];
    INIT_57_reg <= ATTR[`SYSMONE1__INIT_57];
    INIT_58_reg <= ATTR[`SYSMONE1__INIT_58];
    INIT_59_reg <= ATTR[`SYSMONE1__INIT_59];
    INIT_5A_reg <= ATTR[`SYSMONE1__INIT_5A];
    INIT_5B_reg <= ATTR[`SYSMONE1__INIT_5B];
    INIT_5C_reg <= ATTR[`SYSMONE1__INIT_5C];
    INIT_5D_reg <= ATTR[`SYSMONE1__INIT_5D];
    INIT_5E_reg <= ATTR[`SYSMONE1__INIT_5E];
    INIT_5F_reg <= ATTR[`SYSMONE1__INIT_5F];
    INIT_60_reg <= ATTR[`SYSMONE1__INIT_60];
    INIT_61_reg <= ATTR[`SYSMONE1__INIT_61];
    INIT_62_reg <= ATTR[`SYSMONE1__INIT_62];
    INIT_63_reg <= ATTR[`SYSMONE1__INIT_63];
    INIT_64_reg <= ATTR[`SYSMONE1__INIT_64];
    INIT_65_reg <= ATTR[`SYSMONE1__INIT_65];
    INIT_66_reg <= ATTR[`SYSMONE1__INIT_66];
    INIT_67_reg <= ATTR[`SYSMONE1__INIT_67];
    INIT_68_reg <= ATTR[`SYSMONE1__INIT_68];
    INIT_69_reg <= ATTR[`SYSMONE1__INIT_69];
    INIT_6A_reg <= ATTR[`SYSMONE1__INIT_6A];
    INIT_6B_reg <= ATTR[`SYSMONE1__INIT_6B];
    INIT_6C_reg <= ATTR[`SYSMONE1__INIT_6C];
    INIT_6D_reg <= ATTR[`SYSMONE1__INIT_6D];
    INIT_6E_reg <= ATTR[`SYSMONE1__INIT_6E];
    INIT_6F_reg <= ATTR[`SYSMONE1__INIT_6F];
    INIT_70_reg <= ATTR[`SYSMONE1__INIT_70];
    INIT_71_reg <= ATTR[`SYSMONE1__INIT_71];
    INIT_72_reg <= ATTR[`SYSMONE1__INIT_72];
    INIT_73_reg <= ATTR[`SYSMONE1__INIT_73];
    INIT_74_reg <= ATTR[`SYSMONE1__INIT_74];
    INIT_75_reg <= ATTR[`SYSMONE1__INIT_75];
    INIT_76_reg <= ATTR[`SYSMONE1__INIT_76];
    INIT_77_reg <= ATTR[`SYSMONE1__INIT_77];
    INIT_78_reg <= ATTR[`SYSMONE1__INIT_78];
    INIT_79_reg <= ATTR[`SYSMONE1__INIT_79];
    INIT_7A_reg <= ATTR[`SYSMONE1__INIT_7A];
    INIT_7B_reg <= ATTR[`SYSMONE1__INIT_7B];
    INIT_7C_reg <= ATTR[`SYSMONE1__INIT_7C];
    INIT_7D_reg <= ATTR[`SYSMONE1__INIT_7D];
    INIT_7E_reg <= ATTR[`SYSMONE1__INIT_7E];
    INIT_7F_reg <= ATTR[`SYSMONE1__INIT_7F];
    IS_CONVSTCLK_INVERTED_reg = ATTR[`SYSMONE1__IS_CONVSTCLK_INVERTED];
    IS_DCLK_INVERTED_reg = ATTR[`SYSMONE1__IS_DCLK_INVERTED];
   
    trig_attr_chk <= ~trig_attr_chk;
end // always @ (trig_attr)
    
    
// procedures to override, read attribute values

task write_attr;
  input  [`SYSMONE1_ADDR_SZ-1:0] addr;
  input  [`SYSMONE1_DATA_SZ-1:0] data;
begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr;
    trig_dep_attr_chk = #1 ~trig_dep_attr_chk;
   
end
endtask


function [`SYSMONE1_DATA_SZ-1:0] read_attr;
   input  [`SYSMONE1_ADDR_SZ-1:0] addr;
begin
    read_attr = ATTR[addr];
end
endfunction


task commit_attr;
   begin

end
endtask