
+incdir+${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0

${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/AutoFIFOPopControl.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/AXI4CommandDivider.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/AXI4CommandDriver.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/AXI4DataDriver.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/AXI4LiteSlaveInterfaceReadChannel.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/AXI4LiteSlaveInterface.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/AXI4LiteSlaveInterfaceWriteChannel.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/AXI4MasterInterfaceReadChannel.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/AXI4MasterInterface.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/AXI4MasterInterfaceWriteChannel.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/BCHDecoderCommandReception.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/BCHDecoderControl.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/BCHDecoderInputControl.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/BCHDecoderOutputControl.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/BCHDecoderX.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/BCHEncoderCommandChannel.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/BCHEncoderControl.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/BCHEncoderDataChannel.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/BCHEncoderX.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/BRAMPopControl.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/CommandChannelMux.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/CompletionCommandChannel.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/CompletionDataChannel.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/Completion.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/CRC_checker.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/CRC_generator.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/CRC_parallel_m_lfs_XOR.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/CRC_serial_m_lfs_XOR.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DataDriver.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/d_BCH_CS_X.v
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/d_BCH_encoder_parameters.vh
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/d_BCH_encoder_top.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/d_BCH_SC_top.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/d_BCH_SC_X.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DCFIFO_36x16_DR.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DCFIFO_64x16_DR.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/d_CS_evaluation_matrices.v
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/d_CS_parameters.vh
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/d_CS_top.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/Decoder.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DecWidthConverter16to32.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DecWidthConverter32to16.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/Dispatcher.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/d_parallel_m_lfs_XOR.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/d_r_message_buffer_X.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DRSCFIFO_288x16_withCount.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/d_SC_deviders_p_lfs_XOR.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/d_SC_deviders_s_lfs_XOR.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/d_SC_evaluation_matrices.v
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/d_SC_parameters.vh
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/d_serial_m_lfs_XOR.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/EncWidthConverter16to32.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/EncWidthConverter32to16.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/FMCTop.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/LFSR8.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/PageDecoderTop.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/SCFIFO_128x64_withCount.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/SCFIFO_40x64_withCount.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/SCFIFO_64x64_withCount.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/SCFIFO_80x64_withCount.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/ScrambleDecoder.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/ScrambleEncoder.v
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/tiger4_nfc_substrate.1.0.0.f
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/TimeCounter.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/uProgROM.v
${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/V2DatapathClockConverter32.v

////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DCDPRAM16x1280WC:
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DCDPRAM16x1280WC.veo
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DCDPRAM16x1280WC.xci
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DCDPRAM16x1280WC.xml
////
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DPBDCFIFO36x16DR:
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DPBDCFIFO36x16DR.xci
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DPBDCFIFO36x16DR.xml
////
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DPBDCFIFO64x16DR:
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DPBDCFIFO64x16DR.xci
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DPBDCFIFO64x16DR.xml
////
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DPBSCFIFO128x64WC:
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DPBSCFIFO128x64WC.xci
////
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DPBSCFIFO40x64WC:
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DPBSCFIFO40x64WC.xci
////
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DPBSCFIFO64x64WC:
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DPBSCFIFO64x64WC.xci
////
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DPBSCFIFO80x64WC:
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DPBSCFIFO80x64WC.xci
////
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DRSCFIFO288x16WC:
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DRSCFIFO288x16WC.veo
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DRSCFIFO288x16WC.xci
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/DRSCFIFO288x16WC.xml
////${OPENSSD_HOME}/source/hardware/nfc-substrate/tiger4_nfc_substrate-1.0.0/sim
