
+incdir+${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0

////${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/def_axi.vh
////${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/def_nvme.vh
////${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/def_pcie.vh
////${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/def.vh
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/dev_rx_cmd_fifo.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/dev_tx_cmd_fifo.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/dma_cmd_fifo.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/dma_cmd_gen.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/dma_cmd.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/dma_done_fifo.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/dma_done.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/dma_if.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/m_axi_dma.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/m_axi_read.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/m_axi_write.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/nvme_cq_check.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/nvme_irq_handler.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/nvme_irq.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/nvme_pcie.v
////${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_7x_0_core_top
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_cntl_reg.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_cntl_rx_fifo.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_cntl_slave.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_dma_cmd_fifo.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_dma_cmd_gen.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_fc_cntl.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_hcmd_cq_fifo.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_hcmd_cq_req.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_hcmd_cq.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_hcmd_nlb.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_hcmd_slot_mgt.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_hcmd_sq_arb.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_hcmd_sq_fifo.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_hcmd_sq_recv.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_hcmd_sq_req.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_hcmd_sq.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_hcmd_table_cid.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_hcmd_table_prp.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_hcmd_table.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_hcmd.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_irq_gen.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_prp_rx_fifo.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_prp_rx_tag.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_rx_cmd_fifo.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_rx_cpld_sel.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_rx_dma.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_rx_fifo.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_rx_recv.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_rx_req.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_rx_tag.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_rx.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_sq_cmd_fifo.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_sq_rx_fifo.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_sq_rx_tag.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_tans_if.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_tx_arb.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_tx_cmd_fifo.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_tx_dma.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_tx_fifo.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_tx_req.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_tx_tran.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/pcie_tx.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/reg_cpu_pcie_sync.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/s_axi_nvme.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/s_axi_reg.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/s_axi_top.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/sys_rst.v
${OPENSSD_HOME}/source/hardware/nvme/nvme_host_ctrl_8lane-1.0.0/user_top.v
