
+incdir+${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src

////${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/def_nvme.vh
////${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/def_pcie.vh
////${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/def.vh
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/dev_rx_cmd_fifo.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/dev_tx_cmd_fifo.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/dma_cmd_fifo.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/dma_cmd_gen.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/dma_cmd.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/dma_done_fifo.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/dma_done.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/dma_if.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/m_axi_dma.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/m_axi_read.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/m_axi_write.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/nvme_cq_check.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/nvme_irq_handler.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/nvme_irq.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/nvme_pcie.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_cntl_reg.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_cntl_rx_fifo.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_cntl_slave.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_dma_cmd_fifo.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_dma_cmd_gen.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_fc_cntl.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_hcmd_cq_fifo.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_hcmd_cq_req.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_hcmd_cq.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_hcmd_nlb.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_hcmd_slot_mgt.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_hcmd_sq_arb.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_hcmd_sq_fifo.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_hcmd_sq_recv.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_hcmd_sq_req.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_hcmd_sq.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_hcmd_table_cid.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_hcmd_table_prp.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_hcmd_table.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_hcmd.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_irq_gen.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_prp_rx_fifo.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_prp_rx_tag.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_rx_cmd_fifo.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_rx_cpld_sel.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_rx_dma.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_rx_fifo.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_rx_recv.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_rx_req.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_rx_tag.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_rx.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_sq_cmd_fifo.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_sq_rx_fifo.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_sq_rx_tag.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_tans_if.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_tx_arb.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_tx_cmd_fifo.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_tx_dma.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_tx_fifo.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_tx_req.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_tx_tran.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_tx.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/reg_cpu_pcie_sync.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/s_axi_nvme.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/s_axi_reg.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/s_axi_top.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/sys_rst.v
${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/user_top.v

////${OPENSSD_HOME}/project/Predefined/2Ch8Way-1.0.3/IPRepo-1.0.3/NVMeHostController/src/pcie_7x_0_core_top:
////${OPENSSD_HOME}/source/work/rtl/pcie_7x_0_core_top.xci
