
+incdir+${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src

${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/AutoFIFOPopControl.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/AXI4CommandDivider.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/AXI4CommandDriver.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/AXI4DataDriver.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/AXI4LiteSlaveInterfaceReadChannel.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/AXI4LiteSlaveInterface.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/AXI4LiteSlaveInterfaceWriteChannel.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/AXI4MasterInterfaceReadChannel.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/AXI4MasterInterface.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/AXI4MasterInterfaceWriteChannel.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/BCHDecoderCommandReception.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/BCHDecoderControl.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/BCHDecoderInputControl.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/BCHDecoderOutputControl.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/BCHDecoderX.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/BCHEncoderCommandChannel.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/BCHEncoderControl.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/BCHEncoderDataChannel.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/BCHEncoderX.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/BRAMPopControl.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/CommandChannelMux.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/CompletionCommandChannel.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/CompletionDataChannel.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/Completion.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/CRC_checker.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/CRC_generator.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/CRC_parallel_m_lfs_XOR.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/CRC_serial_m_lfs_XOR.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DataDriver.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/d_BCH_CS_X.v
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/d_BCH_encoder_parameters.vh
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/d_BCH_encoder_top.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/d_BCH_SC_top.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/d_BCH_SC_X.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DCFIFO_36x16_DR.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DCFIFO_64x16_DR.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/d_CS_evaluation_matrices.v
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/d_CS_parameters.vh
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/d_CS_top.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/Decoder.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DecWidthConverter16to32.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DecWidthConverter32to16.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/Dispatcher.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/d_parallel_m_lfs_XOR.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/d_r_message_buffer_X.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DRSCFIFO_288x16_withCount.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/d_SC_deviders_p_lfs_XOR.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/d_SC_deviders_s_lfs_XOR.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/d_SC_evaluation_matrices.v
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/d_SC_parameters.vh
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/d_serial_m_lfs_XOR.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/EncWidthConverter16to32.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/EncWidthConverter32to16.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/FMCTop.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/LFSR8.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/PageDecoderTop.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/SCFIFO_128x64_withCount.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/SCFIFO_40x64_withCount.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/SCFIFO_64x64_withCount.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/SCFIFO_80x64_withCount.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/ScrambleDecoder.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/ScrambleEncoder.v
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/tiger4_nfc_substrate.1.0.0.f
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/TimeCounter.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/uProgROM.v
${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/V2DatapathClockConverter32.v

////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DCDPRAM16x1280WC:
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DCDPRAM16x1280WC.veo
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DCDPRAM16x1280WC.xci
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DCDPRAM16x1280WC.xml
////
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DPBDCFIFO36x16DR:
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DPBDCFIFO36x16DR.xci
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DPBDCFIFO36x16DR.xml
////
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DPBDCFIFO64x16DR:
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DPBDCFIFO64x16DR.xci
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DPBDCFIFO64x16DR.xml
////
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DPBSCFIFO128x64WC:
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DPBSCFIFO128x64WC.xci
////
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DPBSCFIFO40x64WC:
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DPBSCFIFO40x64WC.xci
////
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DPBSCFIFO64x64WC:
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DPBSCFIFO64x64WC.xci
////
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DPBSCFIFO80x64WC:
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DPBSCFIFO80x64WC.xci
////
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DRSCFIFO288x16WC:
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DRSCFIFO288x16WC.veo
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DRSCFIFO288x16WC.xci
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/DRSCFIFO288x16WC.xml
////${OPENSSD_HOME}/source/work/rtl/Tiger4NSC/src/sim
