${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NFC_Toggle_Top_DDR100.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPCG_Toggle_bCMD_IDLE.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPCG_Toggle_bCMD_manager.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPCG_Toggle_bCMDMux.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPCG_Toggle_BNC_B_erase.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPCG_Toggle_BNC_P_program.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPCG_Toggle_BNC_P_read_AW30h.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPCG_Toggle_BNC_P_read_DT00h.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPCG_Toggle_MNC_getFT.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPCG_Toggle_MNC_N_init.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPCG_Toggle_MNC_readST.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPCG_Toggle_MNC_setFT.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPCG_Toggle_SCC_N_poe.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPCG_Toggle_SCC_PI_reset.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPCG_Toggle_SCC_PO_reset.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPCG_Toggle_Top.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPCG_Toggle_way_CE_timer.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPhy_Toggle_Physical_Input_DDR100.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPhy_Toggle_Physical_Output_DDR100.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPhy_Toggle_Pinpad.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPhy_Toggle_Top_DDR100.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPM_Toggle_CAL_DDR100.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPM_Toggle_DI_DDR100.v
//////${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPM_Toggle_DO_tADL_DDR100_OTHER.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPM_Toggle_DO_tADL_DDR100.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPM_Toggle_IDLE_DDR100.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPM_Toggle_PHY_B_Reset.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPM_Toggle_PHYOutMux.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPM_Toggle_PIR.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPM_Toggle_POR.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPM_Toggle_TIMER.v
${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/NPM_Toggle_Top_DDR100.v

////${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/c_sub:
////${OPENSSD_HOME}/source/work/rtl/c_sub.xci
////
////${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/SDPRAM_16A9024X32B4512:
////${OPENSSD_HOME}/source/work/rtl/SDPRAM_16A9024X32B4512.xci
////
////${OPENSSD_HOME}/source/work/rtl/V2NFC100DDR/src/SDPRAM_9A16x9B16:
////${OPENSSD_HOME}/source/work/rtl/SDPRAM_9A16x9B16.xci
