///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package vip_axi3_slave_bfm_pkg;
import axi_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter vip_axi3_slave_bfm_VIP_PROTOCOL           = 1;
      parameter vip_axi3_slave_bfm_VIP_READ_WRITE_MODE    = "READ_WRITE";
      parameter vip_axi3_slave_bfm_VIP_INTERFACE_MODE     = 2;
      parameter vip_axi3_slave_bfm_VIP_ADDR_WIDTH         = 32;
      parameter vip_axi3_slave_bfm_VIP_DATA_WIDTH         = 32;
      parameter vip_axi3_slave_bfm_VIP_ID_WIDTH           = 6;
      parameter vip_axi3_slave_bfm_VIP_AWUSER_WIDTH       = 0;
      parameter vip_axi3_slave_bfm_VIP_ARUSER_WIDTH       = 0;
      parameter vip_axi3_slave_bfm_VIP_RUSER_WIDTH        = 0;
      parameter vip_axi3_slave_bfm_VIP_WUSER_WIDTH        = 0;
      parameter vip_axi3_slave_bfm_VIP_BUSER_WIDTH        = 0;
      parameter vip_axi3_slave_bfm_VIP_SUPPORTS_NARROW    = 1;
      parameter vip_axi3_slave_bfm_VIP_HAS_BURST          = 1;
      parameter vip_axi3_slave_bfm_VIP_HAS_LOCK           = 1;
      parameter vip_axi3_slave_bfm_VIP_HAS_CACHE          = 1;
      parameter vip_axi3_slave_bfm_VIP_HAS_REGION         = 1;
      parameter vip_axi3_slave_bfm_VIP_HAS_QOS            = 1;
      parameter vip_axi3_slave_bfm_VIP_HAS_PROT           = 1;
      parameter vip_axi3_slave_bfm_VIP_HAS_WSTRB          = 1;
      parameter vip_axi3_slave_bfm_VIP_HAS_BRESP          = 1;
      parameter vip_axi3_slave_bfm_VIP_HAS_RRESP          = 1;
      parameter vip_axi3_slave_bfm_VIP_HAS_ACLKEN         = 0;
      parameter vip_axi3_slave_bfm_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////


typedef axi_slv_agent #(vip_axi3_slave_bfm_VIP_PROTOCOL, 
                        vip_axi3_slave_bfm_VIP_ADDR_WIDTH,
                        vip_axi3_slave_bfm_VIP_DATA_WIDTH,
                        vip_axi3_slave_bfm_VIP_DATA_WIDTH,
                        vip_axi3_slave_bfm_VIP_ID_WIDTH,
                        vip_axi3_slave_bfm_VIP_ID_WIDTH,
                        vip_axi3_slave_bfm_VIP_AWUSER_WIDTH, 
                        vip_axi3_slave_bfm_VIP_WUSER_WIDTH, 
                        vip_axi3_slave_bfm_VIP_BUSER_WIDTH, 
                        vip_axi3_slave_bfm_VIP_ARUSER_WIDTH,
                        vip_axi3_slave_bfm_VIP_RUSER_WIDTH, 
                        vip_axi3_slave_bfm_VIP_SUPPORTS_NARROW, 
                        vip_axi3_slave_bfm_VIP_HAS_BURST,
                        vip_axi3_slave_bfm_VIP_HAS_LOCK,
                        vip_axi3_slave_bfm_VIP_HAS_CACHE,
                        vip_axi3_slave_bfm_VIP_HAS_REGION,
                        vip_axi3_slave_bfm_VIP_HAS_PROT,
                        vip_axi3_slave_bfm_VIP_HAS_QOS,
                        vip_axi3_slave_bfm_VIP_HAS_WSTRB,
                        vip_axi3_slave_bfm_VIP_HAS_BRESP,
                        vip_axi3_slave_bfm_VIP_HAS_RRESP,
                        vip_axi3_slave_bfm_VIP_HAS_ARESETN) vip_axi3_slave_bfm_slv_t;

typedef axi_slv_mem_agent #(vip_axi3_slave_bfm_VIP_PROTOCOL, 
                        vip_axi3_slave_bfm_VIP_ADDR_WIDTH,
                        vip_axi3_slave_bfm_VIP_DATA_WIDTH,
                        vip_axi3_slave_bfm_VIP_DATA_WIDTH,
                        vip_axi3_slave_bfm_VIP_ID_WIDTH,
                        vip_axi3_slave_bfm_VIP_ID_WIDTH,
                        vip_axi3_slave_bfm_VIP_AWUSER_WIDTH, 
                        vip_axi3_slave_bfm_VIP_WUSER_WIDTH, 
                        vip_axi3_slave_bfm_VIP_BUSER_WIDTH, 
                        vip_axi3_slave_bfm_VIP_ARUSER_WIDTH,
                        vip_axi3_slave_bfm_VIP_RUSER_WIDTH, 
                        vip_axi3_slave_bfm_VIP_SUPPORTS_NARROW, 
                        vip_axi3_slave_bfm_VIP_HAS_BURST,
                        vip_axi3_slave_bfm_VIP_HAS_LOCK,
                        vip_axi3_slave_bfm_VIP_HAS_CACHE,
                        vip_axi3_slave_bfm_VIP_HAS_REGION,
                        vip_axi3_slave_bfm_VIP_HAS_PROT,
                        vip_axi3_slave_bfm_VIP_HAS_QOS,
                        vip_axi3_slave_bfm_VIP_HAS_WSTRB,
                        vip_axi3_slave_bfm_VIP_HAS_BRESP,
                        vip_axi3_slave_bfm_VIP_HAS_RRESP,
                        vip_axi3_slave_bfm_VIP_HAS_ARESETN) vip_axi3_slave_bfm_slv_mem_t;
                        
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      vip_axi3_slave_bfm_slv_t  vip_axi3_slave_bfm_slv;
//      initial begin : START_vip_axi3_slave_bfm_SLAVE
//        vip_axi3_slave_bfm_slv = new("vip_axi3_slave_bfm_slv", `vip_axi3_slave_bfm_PATH_TO_INTERFACE);
//        vip_axi3_slave_bfm_slv.start_slave();
//      end

endpackage : vip_axi3_slave_bfm_pkg
